import type { Metadata } from "next";
import { AlertTriangle, BookOpenCheck, Check, X } from "lucide-react";
import { Section, SectionHeading } from "@/components/ui/section";
import { Callout, FAQ, PageHeader, Timeline } from "@/components/ui/page";
import { Badge } from "@/components/ui/badge";

export const metadata: Metadata = {
  title: "NEA & coursework help",
  description:
    "Stage-by-stage guidance for non-exam assessment: choosing a question, planning, drafting, referencing, and staying inside the JCQ rules.",
};

const SUBJECTS = [
  {
    subject: "History",
    level: "A-Level",
    form: "Independent historical investigation, typically 3,500–4,500 words.",
    pitfall:
      "Choosing a question with no genuine historiographical debate behind it. Without competing interpretations there is nothing to evaluate.",
  },
  {
    subject: "Geography",
    level: "A-Level",
    form: "Independent investigation with your own fieldwork data collection.",
    pitfall:
      "Collecting data before settling the question, then trying to reverse-engineer a rationale for it.",
  },
  {
    subject: "English Literature",
    level: "A-Level",
    form: "Comparative essay across texts, usually including one pre-1900 text.",
    pitfall:
      "Writing two separate essays stapled together instead of a genuinely comparative argument.",
  },
  {
    subject: "Computer Science",
    level: "GCSE & A-Level",
    form: "Programming project with analysis, design, development, testing and evaluation.",
    pitfall:
      "All the marks sit in the written stages, but most time goes into the code. Test evidence is where projects quietly lose grades.",
  },
  {
    subject: "Design & Technology",
    level: "GCSE & A-Level",
    form: "Iterative design portfolio plus a manufactured prototype.",
    pitfall:
      "Undocumented iteration. If a change is not evidenced with annotated photos, it did not happen.",
  },
  {
    subject: "EPQ",
    level: "Level 3",
    form: "5,000-word report or an artefact, plus a production log and presentation.",
    pitfall:
      "Treating the production log as an afterthought — it carries a large share of the marks.",
  },
];

const STAGES = [
  {
    title: "Choose a question you can actually answer",
    meta: "Weeks 1–2",
    body: "Narrow beats broad every time. It needs enough accessible sources to sustain an argument, and a real debate or problem at its centre. Run it past your teacher before you invest any reading time.",
  },
  {
    title: "Build the source base",
    meta: "Weeks 2–5",
    body: "Gather more than you will use, and record the full reference for everything the moment you find it. Reconstructing a bibliography in the final week is miserable and error-prone.",
  },
  {
    title: "Plan against the mark scheme",
    meta: "Week 5",
    body: "Get your board's mark scheme and map each section to the assessment objective it serves. If a planned section scores nothing, cut it.",
  },
  {
    title: "Write the first full draft",
    meta: "Weeks 6–9",
    body: "Complete beats polished. A finished rough draft can be improved; three immaculate paragraphs cannot. Write the introduction last.",
  },
  {
    title: "Take your feedback window",
    meta: "Week 10",
    body: "Boards strictly limit how much help a teacher may give on a draft — usually one round of general, unannotated guidance. Use it deliberately, with specific questions ready.",
  },
  {
    title: "Redraft, reference, proofread",
    meta: "Weeks 11–12",
    body: "Check every citation resolves, the word count is inside the limit, and the bibliography matches your board's required style. Read it aloud once.",
  },
  {
    title: "Submit and authenticate",
    meta: "Deadline",
    body: "You sign a declaration that the work is your own. Your teacher signs to confirm it was produced under the required conditions. Both signatures are a formal statement.",
  },
];

const ALLOWED = [
  "Discussing your question and narrowing it down",
  "Advice on where to look for sources",
  "One round of general feedback on a draft, as your board permits",
  "Guidance on referencing conventions and structure",
  "Help understanding what the mark scheme is asking for",
];

const NOT_ALLOWED = [
  "Anyone else writing or rewriting sections for you",
  "Line-by-line corrections marked onto your draft",
  "Text generated by AI presented as your own",
  "Copying from sources without full citation",
  "Reusing another student's work, past or present",
];

const FAQS = [
  {
    question: "How much help is my teacher allowed to give?",
    answer:
      "Less than most students expect. Under JCQ rules teachers can advise at the planning stage and give one round of general feedback on a draft — telling you an argument is underdeveloped, for instance, but not how to fix it. They cannot annotate corrections onto your work. The precise limits vary by board and subject, so check your specification.",
  },
  {
    question: "Can I use AI to help with my NEA?",
    answer:
      "Not for producing the work. JCQ treats AI-generated content submitted as your own as malpractice, and you sign a declaration confirming the work is yours. Using it to explain a concept you then go and research properly is different from having it draft your analysis — but if in doubt, ask your teacher first and record what you used.",
  },
  {
    question: "What happens if I go over the word count?",
    answer:
      "It depends on the board. Some apply a penalty, others instruct the examiner to stop reading at the limit — which is worse, because your conclusion is where a lot of the evaluation marks live. Treat the limit as hard.",
  },
  {
    question: "Does the NEA get moderated?",
    answer:
      "Yes. Your school marks it against the board's criteria, then the board moderates a sample to check the standard. This can move the whole cohort's marks up or down, which is why matching the mark scheme matters more than impressing your teacher.",
  },
  {
    question: "What counts as plagiarism?",
    answer:
      "Presenting anyone else's words, data, structure or ideas as your own without citation — including paraphrasing closely without a reference. Quote and cite, or write it genuinely in your own words from your own understanding.",
  },
  {
    question: "Can I change my question halfway through?",
    answer:
      "Usually yes, if you move early and your teacher agrees. Sunk cost is not a reason to continue with an unanswerable question — but a change three weeks before the deadline rarely ends well.",
  },
];

export default function NeaPage() {
  return (
    <>
      <PageHeader
        eyebrow="NEA & coursework"
        title="The marks nobody revises for"
        description="Non-exam assessment is often 20% or more of the final grade, and it is the part you have the most control over. Here is how to plan it properly."
      />

      <Section>
        <Callout tone="warning" title="Your specification is the authority">
          <p>
            Word counts, weightings, feedback rules and deadlines differ by
            exam board and by subject, and they are revised between cycles.
            Everything here describes the general shape of NEA work — always
            check your own specification and your school's internal deadlines
            before acting on it.
          </p>
        </Callout>

        <div className="mt-12">
          <SectionHeading
            eyebrow="By subject"
            title="What the NEA looks like in each subject"
            description="And the mistake that most reliably costs marks in each one."
          />
          <ul className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            {SUBJECTS.map((s) => (
              <li key={s.subject} className="card-surface flex flex-col p-6">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <h3 className="font-bold">{s.subject}</h3>
                  <Badge tone="neutral">{s.level}</Badge>
                </div>
                <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                  {s.form}
                </p>
                <div className="mt-4 flex gap-2.5 border-t border-border pt-4">
                  <AlertTriangle
                    className="mt-0.5 size-4 shrink-0 text-warning"
                    aria-hidden="true"
                  />
                  <p className="text-sm leading-relaxed text-muted-foreground">
                    {s.pitfall}
                  </p>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </Section>

      <Section className="border-y border-border bg-background-subtle">
        <SectionHeading
          eyebrow="The process"
          title="A twelve-week shape that works"
          description="Compress it if you must, but keep the order. The failure mode is always starting to write before the question is settled."
        />
        <div className="mt-10 max-w-3xl">
          <Timeline items={STAGES} />
        </div>
      </Section>

      <Section>
        <SectionHeading
          eyebrow="Academic integrity"
          title="Where the line actually is"
          description="NEA malpractice can cost you the qualification, not just the coursework mark. The rules are clearer than most students assume."
        />

        <div className="mt-10 grid gap-4 md:grid-cols-2 md:gap-6">
          <div className="card-surface p-6 md:p-8">
            <h3 className="flex items-center gap-2.5 text-lg font-bold">
              <span className="grid size-8 place-items-center rounded-lg bg-success-soft text-success-soft-foreground">
                <Check className="size-4" aria-hidden="true" />
              </span>
              Legitimate support
            </h3>
            <ul className="mt-6 space-y-3.5">
              {ALLOWED.map((item) => (
                <li key={item} className="flex gap-3 text-sm">
                  <Check
                    className="mt-0.5 size-4 shrink-0 text-success"
                    aria-hidden="true"
                  />
                  {item}
                </li>
              ))}
            </ul>
          </div>

          <div className="card-surface p-6 md:p-8">
            <h3 className="flex items-center gap-2.5 text-lg font-bold">
              <span className="grid size-8 place-items-center rounded-lg bg-destructive-soft text-destructive-soft-foreground">
                <X className="size-4" aria-hidden="true" />
              </span>
              Counts as malpractice
            </h3>
            <ul className="mt-6 space-y-3.5">
              {NOT_ALLOWED.map((item) => (
                <li key={item} className="flex gap-3 text-sm">
                  <X
                    className="mt-0.5 size-4 shrink-0 text-destructive"
                    aria-hidden="true"
                  />
                  <span className="text-muted-foreground">{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <p className="mt-6 text-sm text-muted-foreground">
          Revly supports NEA work by helping you plan, structure and understand
          what is being assessed. It does not write coursework, and neither
          should anyone else.
        </p>
      </Section>

      <Section className="border-t border-border bg-background-subtle">
        <div className="grid gap-10 lg:grid-cols-[1fr_1.4fr] lg:gap-16">
          <div>
            <span className="grid size-11 place-items-center rounded-xl bg-primary-soft text-primary-soft-foreground">
              <BookOpenCheck className="size-5" aria-hidden="true" />
            </span>
            <h2 className="mt-5 text-3xl font-bold">Common questions</h2>
            <p className="mt-4 text-muted-foreground">
              Mostly about how much help you are allowed — which is the thing
              students worry about and ask about least.
            </p>
          </div>
          <FAQ items={FAQS} />
        </div>
      </Section>
    </>
  );
}
